baseURL = "https://luvimsan.github.io/"
locale = "en-US"
title = "Loaay Waheed"
theme = "hugo-bearblog"

# metadata
author = "Loaay Waheed"
copyright = "Copyright © 2026, Loaay Waheed."
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  description = "Personal portfolio and technical blog by luvimsan. open-source, linux, neovim and more..."
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Loaay Waheed"

  hideMadeWithLine = true
  enablePostNavigator = true
  dateFormat = "2006-01-02"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'dracula'
    noClasses = true
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

[outputFormats.terminal]
  mediaType = "text/plain"
  baseName = "index"
  isPlainText = true

[outputs]
  home = ["HTML", "terminal"]

